### ISSUE TITLE
Select not working with 0.14-rc1

### ISSUE THREAD

**Issue by luisrudge** [nikgraf/belle#189]
I have a repro [here](https://github.com/luisrudge/react-repro/tree/belle) (`belle` branch).

![image](https://cloud.githubusercontent.com/assets/941075/10123882/bfc6e8f6-651b-11e5-9285-68dd2b1e5cc2.png)

**Comment by jpuri** [comment]
Hey @luisrudge / @nikgraf ,

I did looked into issue and thats apparently use of method 'isReactElement' in is-component-of-type.js
React RC candidate has got this method removed: https://github.com/facebook/react/pull/4652/files.

This needs to be fixed in belle.

**Comment by luisrudge** [comment]
Thanks for the feedback @jpuri

**Comment by nikgraf** [comment]
hey @luisrudge - we just released a version ready to work with React 0.14. You can get it by running `npm install belle@2.0.0-beta1`. We tested all components. Let us know if you run into any trouble.

**Comment by luisrudge** [comment]
ok. I'll try that. thanks!

**Comment by luisrudge** [comment]
I'm still seeing an error. I updated my [repro repo](https://github.com/luisrudge/react-repro/tree/belle).

![belle](https://cloud.githubusercontent.com/assets/941075/10492108/7e36dcd0-7280-11e5-8605-c14d00a08c7b.gif)

**Comment by jpuri** [comment]
Hey @luisrudge,

Though select is working its showing this error while trying to reposition options (check http://nikgraf.github.io/belle/#/component/select, property: shouldPositionOptions).

PR: https://github.com/nikgraf/belle/pull/207 has the fix.

**Comment by nikgraf** [comment]
@luisrudge now it should work :smile:

**Comment by luisrudge** [comment]
thaaaaaaaaaaaaaaaaaanks :)
